# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e2697dc8c63dc34c5b6e6f97f7ac38f16decc02d1142b41abe0a407837bfcd40282a9e9071c4014c7be25d5eb6c1ee0e2ba2ec1cf1a155a6dd950b0e613d5b6

test:
  secret_key_base: 31e1867ab890cfed115cefb848fc391b2163dbf3ce23fe3af78392ea537425a53a3536256e27dd0096b286d8e06a923bcff7fe11e47b7c1aefe6d28957a629a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
